CREATE TABLE IF NOT EXISTS public.card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_name VARCHAR(255) NOT NULL,
    card_type VARCHAR(255) NOT NULL,
    card_bank VARCHAR(255) NOT NULL,
    has_annual_fee BOOLEAN NOT NULL,
    annual_fee INTEGER,
    rating DOUBLE PRECISION NOT NULL,
    bonus BIGINT,
    bonus_spend BIGINT,
    cashback_flat DOUBLE PRECISION,
    cashback_travel DOUBLE PRECISION,
    cashback_dining DOUBLE PRECISION,
    cashback_grocery DOUBLE PRECISION,
    cashback_gas DOUBLE PRECISION,
    cashback_pharmacy DOUBLE PRECISION,
    cashback_lyft DOUBLE PRECISION,
    cashback_officesupply DOUBLE PRECISION,
    cashback_services DOUBLE PRECISION,
    cashback_brand DOUBLE PRECISION,
    cashback_other DOUBLE PRECISION,
    cashback_choice_hotels BOOLEAN NOT NULL DEFAULT FALSE,
    cashback_hyatt_hotels BOOLEAN NOT NULL DEFAULT FALSE,
    cashback_hilton_hotels BOOLEAN NOT NULL DEFAULT FALSE,
    cashback_marriott_hotels BOOLEAN NOT NULL DEFAULT FALSE,
    credit_score INTEGER
);

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS image_s3_key TEXT;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS image_source_url TEXT;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS cashback_choice_hotels BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS cashback_hyatt_hotels BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS cashback_hilton_hotels BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS cashback_marriott_hotels BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.card
ADD COLUMN IF NOT EXISTS cashback_travel_is_hotel_specific BOOLEAN NOT NULL DEFAULT FALSE;

-- Normalize existing rows so hotel-brand flags are always populated.
UPDATE public.card
SET cashback_choice_hotels = FALSE,
    cashback_hyatt_hotels = FALSE,
    cashback_hilton_hotels = FALSE,
    cashback_marriott_hotels = FALSE;

-- Brand-specific hotel eligibility from card naming.
UPDATE public.card
SET cashback_choice_hotels = TRUE
WHERE LOWER(card_name) LIKE '%choice%';

UPDATE public.card
SET cashback_hyatt_hotels = TRUE
WHERE LOWER(card_name) LIKE '%hyatt%';

UPDATE public.card
SET cashback_hilton_hotels = TRUE
WHERE LOWER(card_name) LIKE '%hilton%';

UPDATE public.card
SET cashback_marriott_hotels = TRUE
WHERE LOWER(card_name) LIKE '%marriott%'
   OR LOWER(card_name) LIKE '%bonvoy%';

-- Mark hotel co-branded cards whose travel cashback only applies at that specific hotel chain.
UPDATE public.card
SET cashback_travel_is_hotel_specific = TRUE
WHERE cashback_choice_hotels = TRUE
   OR cashback_hyatt_hotels = TRUE
   OR cashback_hilton_hotels = TRUE
   OR cashback_marriott_hotels = TRUE;

-- General travel cards earn cashback on all travel, not hotel-specific.
UPDATE public.card
SET cashback_travel_is_hotel_specific = FALSE
WHERE cashback_choice_hotels = FALSE
  AND cashback_hyatt_hotels = FALSE
  AND cashback_hilton_hotels = FALSE
  AND cashback_marriott_hotels = FALSE;
